# Generated by Django 6.0.6 on 2026-06-22 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: 1 kunlik, 1 oylik', max_length=50)),
                ('duration_days', models.IntegerField(help_text='Tarif muddati (kun hisobida, masalan 1, 30, 365)')),
                ('price', models.IntegerField(help_text="Narxi (so'mda)")),
                ('is_active', models.BooleanField(default=True, help_text="Saytda ko'rinishi/ko'rinmasligi")),
                ('order', models.IntegerField(default=0, help_text='Saytda ketma-ketlikda qaysi birinchi chiqishi')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan_name',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apps.subscriptionplan'),
        ),
    ]
