# Generated by Django 6.0.6 on 2026-06-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_subscriptionplan_remove_payment_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='detected_question_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='uploaded', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
