# Generated by Django 6.0.6 on 2026-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
