# Generated by Django 6.0.6 on 2026-07-04 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LobbyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apps.lobby')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_answers', to='apps.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_answers', to='apps.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
